name: Android CI

on:
  push:
    branches: [ android ]
  pull_request:
    branches: [ android ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: cd android && ./gradlew build
    - uses: actions/upload-artifact@v4
      with:
        name: srb2
        path: android/app/build/outputs/apk/
