name: Linux AMD64 AppImage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CC: gcc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt install -y wget libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libminiupnpc-dev libopenmpt-dev

    - name: Build SRB2 Legacy AppImage
      run: chmod +x srb2-legacy-appimage.sh && ./srb2-legacy-appimage.sh
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: srb2legacy-linux-x86_64-appimage-${{ github.sha }}
        path: |
          Sonic_Robo_Blast_2_Legacy_(2.1)-x86_64.AppImage
          src/comptime.h
