name: macOS

on:
  push:
    branches: [ "next", "master", "ci" ]
  pull_request:
    branches: [ "next", "master" ]

env:
  CC: gcc

jobs:
  build:
    continue-on-error: true
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install sdl2 sdl2_mixer game-music-emu miniupnpc libopenmpt cmake

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DSRB2_CONFIG_HAVE_GME=OFF -DSRB2_CONFIG_HAVE_OPENMPT=OFF

    - name: Build SRB2 Legacy
      run: ninja -C build

    - name: Package SRB2 Legacy
      run: ninja -C build package

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: srb2legacy-macOS-${{ github.sha }}
        path: |
          build/
          src/comptime.h
