name: macOS

on:
  push:
    branches: [ "next", "master", "ci" ]
  pull_request:
    branches: [ "next", "master" ]

jobs:
  build:
    continue-on-error: true
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install --formula sdl2 sdl2_mixer game-music-emu miniupnpc libopenmpt cmake

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DSRB2_CONFIG_HAVE_GME=OFF -DSRB2_CONFIG_HAVE_OPENMPT=OFF

    - name: Build SRB2 Legacy
      run: ninja -C build

    - name: Package SRB2 Legacy
      run: |
        VERSION=$(awk '/#define SRB2VERSION/ { gsub(/["\/\*]/, "", $3); print $3 }' src/version.h)
        ninja -C build package
        codesign --deep --force --sign - build/_CPack_Packages/Darwin/TGZ/SRB2-$VERSION-Darwin/Sonic\ Robo\ Blast\ 2\ Legacy.app

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: srb2legacy-macOS-aarch64-${{ github.sha }}
        path: |
          build/_CPack_Packages/Darwin/TGZ/SRB2-*-Darwin*/
          src/comptime.h
