name: Windows x86

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PREFIX: i686-w64-mingw32

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4.2.2

     - name: Install Dependencies
       run: sudo apt update && sudo apt install -y gcc-mingw-w64-i686 binutils-mingw-w64-i686

     - name: Build SRB2 Legacy
       run: make -C src/ --keep-going  -j$(nproc) MINGW=1

     - name: Upload Artifacts
       uses: actions/upload-artifact@v4.6.2
       with:
        name: srb2legacy-windows-x86
        path: |
          bin/
          src/comptime.h
